stages:
  - test
  - build
  - deploy

# Etap testowania
test:
  stage: test
  image: python:3.12
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest tests/  # Uruchomienie testów jednostkowych za pomocą pytest
  artifacts:
    paths:
      - pytest.xml  # Zapisanie wyników testów, jeśli są wymagane

# Etap budowania aplikacji
build:
  stage: build
  image: python:3.12
  before_script:
    - pip install -r requirements.txt
  script:
    - python setup.py install  # Budowanie aplikacji (w zależności od tego, jak ma być zbudowana)
  artifacts:
    paths:
      - dist/  # Zapisanie artefaktów budowania, np. paczek aplikacji

# Etap wdrożenia
deploy:
  stage: deploy
  image: python:3.12
  before_script:
    - pip install -r requirements.txt
  script:
    - python deploy.py  # Skrypt wdrożeniowy
  only:
    - master  # Wdrażanie tylko z gałęzi master
