name: Koncowe CI

on:
  push:
    branches:
      - Koncowe
  pull_request:
    branches:
      - Koncowe

jobs:
  test:
    name: Run Tests and Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/


  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Code
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_ALL_CODEBASE: false
